version: "1.0"
info:
  model: int-scaffold
packages:
- name: Mcp_ganeshProject
  gitServerName: mcp_ganesh
  gitUrl: https://github.com/Ganesh-Jathar-Git
  gitUsername: Ganesh-Jathar-Git
  gitBranch: main
- name: WxMCPServer
  gitServerName: mcp_ganesh
  gitUrl: https://github.com/IBM
  gitUsername: Ganesh-Jathar-Git
  gitBranch: main
